replicaCount: 1
image:
  pullPolicy: IfNotPresent
  repository: r.cfcr.io/plmercereau/default/graphql-server
service:
  name: graphql-server
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
  - graphql.platyplus.io
  tls:
  - hosts:
    - graphql.platyplus.io
basedomain: platyplus.io
prisma:
#  TODO
  enabled: true
  imagePullPolicy: "IfNotPresent"
  nameOverride: prisma
  database:
    connector: postgres
    name: prisma
    user: postgres
    password: "Q/KARXveNYi8txbWFxbzfj+PN2SwU20MvxEYOIwNSZf/SiXyuH5y5xlrxpcbx1SrxogmgyueBhSgUqET/VzrGp4j1l4/6/mM9OLSc4zaR3rdMSUU9ZzRZW5xHWHP/Ceyhjx8CEptaAlAqexD8WDWaWiSj1NZZgb5FQClKb3rakk="
    host: "127.0.0.1"
    port: "5432"
    googleCloudSQL:
      enabled: true
      host: "platyplus-0402:europe-west1:prisma-prod"
