apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  server: {{ .Values.prismaServer }}
  service: {{ template "fullname" . }}
  stage: {{ default "production" .Values.prismaStage }}
